/**:
    ros__parameters:
        # Generic parameters
        use_sim_time: false
        namespace: ""
        nodeName: "rv2_camera"          # rv2_sensors only
        id: "0"                         # rv2_sensors only

        devManageService: "devmanage_0" # Service name
        devInterface: "eno1"            # rv2_sensors only
        procStatusRegPeriod_ms: 200.0   # Procedure status registration period

        qosService: "qos_0"             # Service name
        qosDirPath: "qos"               # rv2_sensors only

        safetyService: ""               # Service name

        timesyncService: ""             # Service name
        timesyncPeriod_ms: 0.0          # rv2_sensors only
        timesyncAccuracy_ms: 0.0        # rv2_sensors only
        timesyncWaitService: false      # rv2_sensors only

        # Package parameters

        ## Topic publisher parameters
        topicName: "camera_0"
        publishWidth: 1920
        publishHeight: 1080
        useCompression: true
        compressionQuality: 80

        ## Camera parameters
        cameraCapID: 0
        cameraAutoSetting: true
        cameraFPS: 30.0 # Camera frame rate (cameraAutoFrameSetting: false)
        cameraWidth: 640 # Input resolution (cameraAutoFrameSize: false)
        cameraHeight: 480
        cameraUseColor: true

        ## Procedure timeout parameters
        imagePublishProcTimeout_ms: 100.0 # 10fps
        caminfoPublishProcTimeout_ms: 2000.0 # 0.5fps
