launch:
    params: "common.yaml"
    launch: "zed_camera.launch.py"
    startup_location: "${HOME}" # Leave empty if not needed.
    use_root: false
    gui_mode: false

launch_params: # Override common.yaml parameters here
    camera_model: "zed2i"

network:
    interface: "enp2s0"
    internet_required: false
