/**:
    ros__parameters:
        # Generic parameters
        use_sim_time: false
        namespace: ""
        nodeName: "rv2_gnss"            # rv2_sensors only
        id: "0"                         # rv2_sensors only

        devManageService: "devmanage_0" # Service name
        devInterface: "eno1"            # rv2_sensors only
        procStatusRegPeriod_ms: 500.0   # Procedure status registration period

        qosService: "qos_0"             # Service name
        qosDirPath: "qos"               # rv2_sensors only

        safetyService: ""               # Service name

        timesyncService: ""             # Service name
        timesyncPeriod_ms: 0.0          # rv2_sensors only
        timesyncAccuracy_ms: 0.0        # rv2_sensors only
        timesyncWaitService: false      # rv2_sensors only

        # Package parameters

        ## Topic publisher parameters
        topicName: "gnss_0"
        publishPeriod_ms: 500.0

        ## GPSD parameters
        gpsdHost: "localhost"
        gpsdPort: 2947

        ## Procedure timeout parameters
        gpsModuleProcTimeout_ms: 6000.0
        msgPublishProcTimeout_ms: 1000.0
