/**:
    ros__parameters:
        # Generic parameters
        use_sim_time: false
        namespace: ""
        nodeName: "rv2_ultrasound"      # rv2_sensors only
        id: "0"                         # rv2_sensors only

        devManageService: "devmanage_0" # Service name
        devInterface: "eno1"            # rv2_sensors only
        procStatusRegPeriod_ms: 200.0   # Procedure status registration period

        qosService: "qos_0"             # Service name
        qosDirPath: "qos"               # rv2_sensors only

        safetyService: ""               # Service name

        timesyncService: ""             # Service name
        timesyncPeriod_ms: 0.0          # rv2_sensors only
        timesyncAccuracy_ms: 0.0        # rv2_sensors only
        timesyncWaitService: false      # rv2_sensors only

        # Package parameters

        ## Topic publisher parameters
        topicName: "ultrasound"
        topicIds: [0.0, 1.0, 2.0, 3.0]
        publishPeriod_ms: 100.0

        ## Device parameters
        devicePath : "/dev/ttyACM0"
        deviceBaud : 9600
        minRange : 0.2 # m
        maxRange : 8.0 # m
        fov : 15.0 # degree

        ## Procedure timeout parameters
        serialModuleProcTimeout_ms: 100.0
        msgPublishProcTimeout_ms: 200.0
